#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

RUN_ID=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-id)
      RUN_ID="${2:-}"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${RUN_ID}" ]]; then
  RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
fi

SAFE_RUN_ID="$(printf "%s" "${RUN_ID}" | tr -cs 'A-Za-z0-9._-' '-')"
ARTIFACT_ROOT="${AI_AGENT_ARTIFACT_ROOT:-${PROJECT_ROOT}/artifacts}"
RUN_DIR="${AI_AGENT_RUN_DIR:-${ARTIFACT_ROOT}/${SAFE_RUN_ID}}"
BACKEND_HOST="${AI_AGENT_BACKEND_HOST:-127.0.0.1}"
BACKEND_PORT="${AI_AGENT_BACKEND_PORT:-8765}"
BACKEND_URL="${AI_AGENT_BACKEND_URL:-ws://${BACKEND_HOST}:${BACKEND_PORT}}"

mkdir -p "${RUN_DIR}"

if [[ -d "${PROJECT_ROOT}/.venv/bin" ]]; then
  case ":${PATH}:" in
    *":${PROJECT_ROOT}/.venv/bin:"*) ;;
    *) export PATH="${PROJECT_ROOT}/.venv/bin:${PATH}" ;;
  esac
fi

export AI_AGENT_RUN_ID="${SAFE_RUN_ID}"
export AI_AGENT_RUN_DIR="${RUN_DIR}"
export AI_AGENT_BACKEND_HOST="${BACKEND_HOST}"
export AI_AGENT_BACKEND_PORT="${BACKEND_PORT}"
export AI_AGENT_BACKEND_URL="${BACKEND_URL}"
export AI_AGENT_ARTIFACT_DIR="${RUN_DIR}"
export AI_AGENT_DEBUG_JSON_LOGS="${AI_AGENT_DEBUG_JSON_LOGS:-0}"
export AI_AGENT_DEBUG_PROTOCOL_TRACE="${AI_AGENT_DEBUG_PROTOCOL_TRACE:-0}"
export AI_AGENT_DEBUG_PROTOCOL_TRACE_MAX_BYTES="${AI_AGENT_DEBUG_PROTOCOL_TRACE_MAX_BYTES:-4096}"
export AI_AGENT_DEBUG_DB_METRICS="${AI_AGENT_DEBUG_DB_METRICS:-0}"
export AI_AGENT_DEBUG_DB_METRICS_INTERVAL_SECONDS="${AI_AGENT_DEBUG_DB_METRICS_INTERVAL_SECONDS:-15}"
export AI_AGENT_DEBUG_FRONTEND_LOGS="${AI_AGENT_DEBUG_FRONTEND_LOGS:-0}"
export AI_AGENT_IPC_MAX_CLIENTS="${AI_AGENT_IPC_MAX_CLIENTS:-64}"
export PYTHONASYNCIODEBUG="${PYTHONASYNCIODEBUG:-0}"
export PYTHONFAULTHANDLER="${PYTHONFAULTHANDLER:-1}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"

{
  echo "AI_AGENT_RUN_ID=${AI_AGENT_RUN_ID}"
  echo "AI_AGENT_RUN_DIR=${AI_AGENT_RUN_DIR}"
  echo "AI_AGENT_BACKEND_HOST=${AI_AGENT_BACKEND_HOST}"
  echo "AI_AGENT_BACKEND_PORT=${AI_AGENT_BACKEND_PORT}"
  echo "AI_AGENT_BACKEND_URL=${AI_AGENT_BACKEND_URL}"
  echo "AI_AGENT_ARTIFACT_DIR=${AI_AGENT_ARTIFACT_DIR}"
  echo "AI_AGENT_DEBUG_JSON_LOGS=${AI_AGENT_DEBUG_JSON_LOGS}"
  echo "AI_AGENT_DEBUG_PROTOCOL_TRACE=${AI_AGENT_DEBUG_PROTOCOL_TRACE}"
  echo "AI_AGENT_DEBUG_PROTOCOL_TRACE_MAX_BYTES=${AI_AGENT_DEBUG_PROTOCOL_TRACE_MAX_BYTES}"
  echo "AI_AGENT_DEBUG_DB_METRICS=${AI_AGENT_DEBUG_DB_METRICS}"
  echo "AI_AGENT_DEBUG_DB_METRICS_INTERVAL_SECONDS=${AI_AGENT_DEBUG_DB_METRICS_INTERVAL_SECONDS}"
  echo "AI_AGENT_DEBUG_FRONTEND_LOGS=${AI_AGENT_DEBUG_FRONTEND_LOGS}"
  echo "AI_AGENT_IPC_MAX_CLIENTS=${AI_AGENT_IPC_MAX_CLIENTS}"
  echo "PYTHONASYNCIODEBUG=${PYTHONASYNCIODEBUG}"
  echo "PYTHONFAULTHANDLER=${PYTHONFAULTHANDLER}"
  echo "PYTHONUNBUFFERED=${PYTHONUNBUFFERED}"
} > "${RUN_DIR}/env.snapshot"

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "run_id=${AI_AGENT_RUN_ID}"
  echo "run_dir=${AI_AGENT_RUN_DIR}"
  echo "backend_url=${AI_AGENT_BACKEND_URL}"
fi
